version: '3'

services:
  db:
    image: postgres:latest
    container_name: postgres
    ports:
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=albums
    volumes:
      - database_dockerizing:/var/lib/postgresql/data
      - ./dbshell:/docker-entrypoint-initdb.d/
      - ./dbshell/db.sql:/docker-entrypoint-initdb.d/db.sql

    networks:
      - fullstack
  api:
    container_name: api
    build: .
    ports:
      - 8080:8080
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=albums
    volumes:
      - api_volume:/usr/src/app/
    depends_on:
      - db
    networks:
      - fullstack
volumes:
  database_dockerizing:
  api_volume:


networks:
  fullstack:
    driver: bridge
